import { useEffect, useRef, useState } from 'react';
import { useAppStore, currentEvent, inventoryItems } from '../../app/appStore';
import { canChooseEvent, deriveEventOffers, previewEventChoice, previewRecruitment } from '../../game/core/progression/events';
import type { EventSelection } from '../../game/content/events';
import { getRelic } from '../../game/content/relics';
import { getItem } from '../../game/content/items';
import { getAbility, getCharacter } from '../../game/content/characters';
import { GameHeader } from '../../ui/components/GameHeader';
import { PaperButton } from '../../ui/components/PaperButton';

type Step='choices'|'trade-inputs'|'trade-offer'|'pawn-input'|'train-offer'|'press-input'|'recruit-candidate'|'recruit-outgoing'|'recruit-upgrades'|'confirm';

function PressOdds(){
  return <ul className="press-odds"><li>45%: unowned Uncommon relic</li><li>35%: different unowned Common relic</li><li>20%: your selected relic is destroyed</li></ul>;
}

function CharacterDetails({characterId}:{characterId:string}){
  const character=getCharacter(characterId);
  return <div className="recruit-character-details"><strong>{character.displayName}</strong><span>{character.role} - {character.affinity}</span><span>HP {character.stats.maxHp} | POW {character.stats.power} | GRD {character.stats.guard} | SPD {character.stats.speed}</span><ul>{character.abilities.map(id=>{const ability=getAbility(id);return <li key={id}><strong>{ability.name}</strong>: {ability.description}</li>;})}</ul><p><strong>Passive: {character.passive.name}</strong>: {character.passive.description}</p></div>;
}

export function EventScreen(){
  const run=useAppStore(s=>s.run)!;const event=currentEvent(run);const choose=useAppStore(s=>s.chooseEvent);const result=useAppStore(s=>s.eventResult);const finish=useAppStore(s=>s.finishEvent);const error=useAppStore(s=>s.error);const isResolving=useAppStore(s=>s.isResolving);
  const [step,setStep]=useState<Step>('choices');const [choiceId,setChoiceId]=useState<string|null>(null);const [draft,setDraft]=useState<EventSelection|null>(null);const origin=useRef<HTMLButtonElement|null>(null);const originChoiceId=useRef<string|null>(null);const heading=useRef<HTMLHeadingElement|null>(null);
  useEffect(()=>{setStep('choices');setChoiceId(null);setDraft(null);},[run.currentNodeId]);
  useEffect(()=>{if(step!=='choices')heading.current?.focus();},[step]);
  useEffect(()=>{const cancel=(e:KeyboardEvent)=>{if(e.key==='Escape'&&step!=='choices'){e.preventDefault();setStep('choices');setDraft(null);setChoiceId(null);}};window.addEventListener('keydown',cancel);return()=>window.removeEventListener('keydown',cancel);},[step]);
  if(!event)return null;
  const offers=deriveEventOffers(run,run.currentNodeId!);const inventory=inventoryItems(run);
  const ownedCommonRelics=run.relicIds.flatMap(id=>{try{const relic=getRelic(id);return relic.rarity==='common'?[relic]:[];}catch{return[];}});
  const recruit=draft?.kind==='recruit'?draft:null;const outgoing=recruit?run.party.find(member=>member.characterId===recruit.outgoingCharacterId):undefined;const required=outgoing?.upgradedAbilities.length??0;
  const recruitLegal=choiceId&&recruit?canChooseEvent(run,event.id,choiceId,recruit):undefined;const recruitPreview=recruitLegal?.allowed&&recruit?previewRecruitment(run,recruit):undefined;
  const cancel=()=>{setStep('choices');setChoiceId(null);setDraft(null);};
  const back=()=>{if(step==='trade-offer')return setStep('trade-inputs');if(step==='recruit-outgoing')return setStep('recruit-candidate');if(step==='recruit-upgrades')return setStep('recruit-outgoing');if(step==='confirm'&&choiceId==='recruit')return setStep(required?'recruit-upgrades':'recruit-outgoing');if(step==='confirm'&&choiceId&&event.choices.find(c=>c.id===choiceId)?.effects.some(e=>e.kind==='pressRelic'))return setStep('press-input');cancel();};
  const confirm=()=>{if(choiceId&&draft&&canChooseEvent(run,event.id,choiceId,draft).allowed&&!isResolving)void choose(choiceId,draft);};
  const special=(id:string,target:Step,button:HTMLButtonElement)=>{origin.current=button;originChoiceId.current=id;setChoiceId(id);setStep(target);};
  let controls:React.ReactNode;
  if(step==='choices')controls=<div className="event-choices">{event.choices.filter(c=>!c.requiresCharacterId||run.party.some(m=>m.characterId===c.requiresCharacterId)).map(c=>{const legal=canChooseEvent(run,event.id,c.id);const preview=previewEventChoice(run,event.id,c.id);const press=c.effects.some(e=>e.kind==='pressRelic');const recruitment=c.effects.some(e=>e.kind==='recruit');const target=recruitment?'recruit-candidate':press?'press-input':c.id==='trade'?'trade-inputs':c.id==='pawn'?'pawn-input':'train-offer';const multi=recruitment||press||c.id==='trade'||c.id==='pawn'||c.id==='train';return <button key={c.id} ref={node=>{if(c.id===originChoiceId.current){origin.current=node;node?.focus();}}} aria-disabled={!legal.allowed||isResolving} onClick={e=>{if(!legal.allowed||isResolving)return;multi?special(c.id,target,e.currentTarget):void choose(c.id);}}><strong>{c.label}</strong><span>{c.hint}{preview.hpDelta||preview.ppDelta?' ('+preview.hpDelta+' HP, '+preview.ppDelta+' PP across the party)':''}</span><em>{isResolving?'RESOLVING...':legal.allowed?'CHOOSE':legal.reason}</em></button>;})}</div>;
  else controls=<div className="event-selection"><h2 ref={heading} tabIndex={-1}>{step==='trade-inputs'?'Choose two items':step==='trade-offer'?'Choose your offer':step==='pawn-input'?'Choose an item to pawn':step==='train-offer'?'Choose an ability to train':step==='press-input'?'Choose a relic to press':step==='recruit-candidate'?'Choose a recruit':step==='recruit-outgoing'?'Choose a party member to replace':step==='recruit-upgrades'?'Choose inherited upgrades':'Confirm choice'}</h2>
    {step==='trade-inputs'&&<><p>Selected {draft?.kind==='tradeItems'?draft.itemIds.length:0}/2</p>{inventory.map(entry=>{const ids=draft?.kind==='tradeItems'?[...draft.itemIds]:[];const count=ids.filter(id=>id===entry.itemId).length;const update=(next:string[])=>setDraft(next.length===2?{kind:'tradeItems',itemIds:next as [string,string],offeredItemId:''}:null);return <div key={entry.itemId}><strong>{entry.definition.name}</strong> - owned {entry.quantity} - selected {count} <button type="button" aria-label={'Add '+entry.definition.name} disabled={ids.length>=2||count>=entry.quantity} onClick={()=>update([...ids,entry.itemId])}>ADD</button> <button type="button" aria-label={'Remove '+entry.definition.name} disabled={!count} onClick={()=>update(ids.filter((id,index)=>id!==entry.itemId||index!==ids.lastIndexOf(entry.itemId)))}>REMOVE</button></div>;})}<PaperButton variant="ink" onClick={()=>draft?.kind==='tradeItems'&&setStep('trade-offer')} disabled={draft?.kind!=='tradeItems'}>NEXT</PaperButton></>}
    {step==='trade-offer'&&<>{offers.itemIds.map(id=>{const item=getItem(id);return <label key={id}><input type="radio" name="offer" checked={draft?.kind==='tradeItems'&&draft.offeredItemId===id} onChange={()=>draft?.kind==='tradeItems'&&setDraft({...draft,offeredItemId:id})}/><strong>{item.name}</strong> {item.description}</label>;})}<PaperButton variant="ink" onClick={()=>setStep('confirm')} disabled={draft?.kind!=='tradeItems'||!draft.offeredItemId}>REVIEW TRADE</PaperButton></>}
    {step==='pawn-input'&&<>{inventory.map(entry=><label key={entry.itemId}><input type="radio" name="pawn" checked={draft?.kind==='pawnItem'&&draft.itemId===entry.itemId} onChange={()=>setDraft({kind:'pawnItem',itemId:entry.itemId})}/>{entry.definition.name} - owned {entry.quantity} - +{Math.floor(entry.definition.price/2)} coins</label>)}<PaperButton variant="ink" onClick={()=>setStep('confirm')} disabled={draft?.kind!=='pawnItem'}>REVIEW PAWN</PaperButton></>}
    {step==='train-offer'&&<>{offers.upgrades.map(offer=>{const ability=getAbility(offer.abilityId);return <label key={offer.characterId+':'+offer.abilityId}><input type="radio" name="training" checked={draft?.kind==='upgradeAbility'&&draft.abilityId===offer.abilityId&&draft.characterId===offer.characterId} onChange={()=>setDraft({kind:'upgradeAbility',...offer})}/><strong>{getCharacter(offer.characterId).displayName}: {ability.name}</strong> {ability.description} Upgrade: {ability.upgrade.description}</label>;})}<p>Cost: 22 coins and 8% Max HP from each living ally.</p><PaperButton variant="ink" onClick={()=>setStep('confirm')} disabled={draft?.kind!=='upgradeAbility'}>REVIEW TRAINING</PaperButton></>}
    {step==='press-input'&&<><p>Choose one owned Common relic.</p>{choiceId==='risk'&&<PressOdds/>}<div className="press-relic-options">{ownedCommonRelics.map(relic=><label key={relic.id} className={draft?.kind==='pressRelic'&&draft.relicId===relic.id?'selected':''}><input type="radio" name="press-input" checked={draft?.kind==='pressRelic'&&draft.relicId===relic.id} onChange={()=>setDraft({kind:'pressRelic',relicId:relic.id})}/><span><strong>{relic.name}</strong><small>COMMON - {relic.description}</small></span></label>)}</div><PaperButton variant="ink" onClick={()=>setStep('confirm')} disabled={draft?.kind!=='pressRelic'||!choiceId||!canChooseEvent(run,event.id,choiceId,draft).allowed}>REVIEW PRESS</PaperButton></>}
    {step==='recruit-candidate'&&<>{offers.recruitIds.map(id=><label key={id} className="recruit-option"><input type="radio" name="candidate" checked={recruit?.candidateId===id} onChange={()=>setDraft({kind:'recruit',candidateId:id,outgoingCharacterId:'',upgradeIds:[]})}/><CharacterDetails characterId={id}/></label>)}<PaperButton variant="ink" disabled={!recruit?.candidateId} onClick={()=>setStep('recruit-outgoing')}>NEXT</PaperButton></>}
    {step==='recruit-outgoing'&&<>{run.party.map(member=>{const character=getCharacter(member.characterId);return <label key={member.characterId} className="recruit-option"><input type="radio" name="outgoing" checked={recruit?.outgoingCharacterId===member.characterId} onChange={()=>recruit&&setDraft({...recruit,outgoingCharacterId:member.characterId,upgradeIds:[]})}/><CharacterDetails characterId={member.characterId}/><span>Current HP {member.hp}/{character.stats.maxHp} - upgrades {member.upgradedAbilities.length}</span></label>;})}<PaperButton variant="ink" disabled={!outgoing} onClick={()=>setStep(required?'recruit-upgrades':'confirm')}>REVIEW REPLACEMENT</PaperButton></>}
    {step==='recruit-upgrades'&&recruit&&<><p>Selected {recruit.upgradeIds.length}/{required}. Choose upgrades for the incoming recruit.</p>{getCharacter(recruit.candidateId).abilities.map(id=>{const ability=getAbility(id);const checked=recruit.upgradeIds.includes(id);return <label key={id}><input type="checkbox" checked={checked} disabled={!checked&&recruit.upgradeIds.length>=required} onChange={()=>setDraft({...recruit,upgradeIds:checked?recruit.upgradeIds.filter(upgradeId=>upgradeId!==id):[...recruit.upgradeIds,id]})}/><strong>{ability.name}</strong> - {ability.upgrade.description}</label>;})}<PaperButton variant="ink" disabled={recruit.upgradeIds.length!==required} onClick={()=>setStep('confirm')}>REVIEW REPLACEMENT</PaperButton></>}
    {step==='confirm'&&<>{recruitPreview?<div className="recruit-preview"><CharacterDetails characterId={recruitPreview.member.characterId}/><p>Final HP: {recruitPreview.member.hp}/{getCharacter(recruitPreview.member.characterId).stats.maxHp}</p><ul>{getCharacter(recruitPreview.member.characterId).abilities.map(id=>{const ability=getAbility(id);const maximum=ability.maxPP+(recruitPreview.member.upgradedAbilities.includes(id)?ability.upgrade.maxPPDelta??0:0);return <li key={id}>{ability.name}: {recruitPreview.member.abilityPP[id]}/{maximum}{recruitPreview.member.upgradedAbilities.includes(id)?' (upgraded)':''}</li>;})}</ul>{recruitPreview.warnings.map(warning=><p className="inline-error" key={warning}>{warning}</p>)}</div>:<><p>{draft?.kind==='pressRelic'?'Press '+getRelic(draft.relicId).name+'.':draft?.kind==='tradeItems'?'Trade two items for '+getItem(draft.offeredItemId).name+'.':draft?.kind==='pawnItem'?'Pawn '+getItem(draft.itemId).name+' for +'+Math.floor(getItem(draft.itemId).price/2)+' coins.':'Train '+(draft?.kind==='upgradeAbility'?getAbility(draft.abilityId).name:'')+'.'}</p>{draft?.kind==='pressRelic'&&choiceId==='risk'&&<PressOdds/>}</>}<PaperButton variant="ink" onClick={confirm} disabled={!draft||isResolving||(choiceId==='recruit'&&!recruitPreview)}>{draft?.kind==='pressRelic'?(choiceId==='risk'?'CONFIRM RISKY PRESS':'CONFIRM EXCHANGE'):'CONFIRM'}</PaperButton></>}
    <PaperButton variant="ink" onClick={back}>{step==='trade-offer'||step==='recruit-outgoing'||step==='recruit-upgrades'||(step==='confirm'&&choiceId==='recruit')?'BACK':'CANCEL'}</PaperButton></div>;
  return <main className={'screen event-screen event-theme-'+event.theme}><GameHeader title={event.title} subtitle="Read the consequence before choosing."/><section className="event-theatre"><div className="event-backdrop" aria-hidden="true"><i className="event-shape a"/><i className="event-shape b"/><i className="event-shape c"/><i className="event-prop"/></div><div className="event-poster"><span className="event-kicker">ROADSIDE EVENT</span><p className="event-copy">{event.text}</p>{result?<div className="event-result"><strong>RESULT</strong><p>{result}</p><PaperButton variant="ink" onClick={finish}>BACK TO ROUTE</PaperButton></div>:controls}{error&&<p className="inline-error" role="alert">{error}</p>}</div></section></main>;
}
