import type { AbilityDefinition, CharacterDefinition } from '../core/types.js';

const ability = (value: AbilityDefinition): AbilityDefinition => value;

export const ABILITIES: AbilityDefinition[] = [
  ability({ id:'knuckle-up', name:'Knuckle Up', affinity:'might', maxPP:18, target:'enemy-one', description:'A reliable close-range strike.', effects:[{kind:'damage', power:70, target:'enemy-one'}], upgrade:{description:'Power rises to 82.', powerDelta:12} }),
  ability({ id:'yosi', name:'Yosi', affinity:'trick', maxPP:8, target:'enemy-one', accuracy:90, description:'A smoky hit that Blinds for 2 turns.', effects:[{kind:'damage', power:45, target:'enemy-one', accuracy:90},{kind:'status', target:'enemy-one', statusId:'blind', duration:2, accuracy:90}], upgrade:{description:'Blind lasts 3 turns.', durationDelta:1} }),
  ability({ id:'patch-up', name:'Patch Up', affinity:'neutral', maxPP:6, target:'ally-one', description:'Heal one ally for 30% of Max HP.', effects:[{kind:'heal', target:'ally-one', percentMaxHp:0.30, mechanicId:'earl-first-heal'}], upgrade:{description:'Healing rises to 36% Max HP.', healScale:1.2} }),
  ability({ id:'adrenaline', name:'Adrenaline', affinity:'neutral', maxPP:4, target:'self', description:'Gain Strength for 2 turns and heal 12% Max HP.', effects:[{kind:'status', target:'self', statusId:'strength', duration:2},{kind:'heal', target:'self', percentMaxHp:0.12, mechanicId:'earl-first-heal'}], upgrade:{description:'Strength lasts 3 turns.', durationDelta:1} }),

  ability({ id:'cutlass', name:'Cutlass', affinity:'might', maxPP:18, target:'enemy-one', description:'A dependable pirate slash.', effects:[{kind:'damage', power:75, target:'enemy-one'}], upgrade:{description:'Power rises to 87.', powerDelta:12} }),
  ability({ id:'broadside', name:'Broadside', affinity:'tech', maxPP:7, target:'enemy-all', description:'Blast every enemy.', effects:[{kind:'damage', power:55, target:'enemy-all'}], upgrade:{description:'Power rises to 64.', powerDelta:9} }),
  ability({ id:'plunder', name:'Plunder', affinity:'trick', maxPP:6, target:'enemy-one', description:'A KO grants 12 bonus coins.', effects:[{kind:'damage', power:60, target:'enemy-one', mechanicId:'plunder'},{kind:'grantCoins', amount:12, trigger:'ko'}], upgrade:{description:'Power rises to 72.', powerDelta:12} }),
  ability({ id:'boarding-rush', name:'Boarding Rush', affinity:'might', maxPP:5, target:'enemy-one', description:'Hits 25% harder against targets below half HP.', effects:[{kind:'damage', power:90, target:'enemy-one', mechanicId:'boarding-rush'}], upgrade:{description:'Power rises to 102.', powerDelta:12} }),

  ability({ id:'rifle-burst', name:'Rifle Burst', affinity:'tech', maxPP:16, target:'enemy-one', description:'Reliable ranged fire.', effects:[{kind:'damage', power:72, target:'enemy-one'}], upgrade:{description:'Power rises to 84.', powerDelta:12} }),
  ability({ id:'grenade', name:'Grenade', affinity:'tech', maxPP:7, target:'enemy-all', description:'Explosive damage to all enemies.', effects:[{kind:'damage', power:50, target:'enemy-all'}], upgrade:{description:'Power rises to 60.', powerDelta:10} }),
  ability({ id:'suppressing-fire', name:'Suppressing Fire', affinity:'tech', maxPP:7, target:'enemy-one', accuracy:95, description:'Damage and Slow for 2 turns.', effects:[{kind:'damage', power:60, target:'enemy-one', accuracy:95},{kind:'status', target:'enemy-one', statusId:'slow', duration:2, accuracy:95}], upgrade:{description:'Slow lasts 3 turns.', durationDelta:1} }),
  ability({ id:'rally', name:'Rally', affinity:'neutral', maxPP:5, target:'ally-all', description:'All allies gain Strength for 2 turns.', effects:[{kind:'status', target:'ally-all', statusId:'strength', duration:2}], upgrade:{description:'Strength lasts 3 turns.', durationDelta:1} }),

  ability({ id:'deck-gun', name:'Deck Gun', affinity:'tech', maxPP:16, target:'enemy-one', description:'A solid naval gun strike.', effects:[{kind:'damage', power:68, target:'enemy-one'}], upgrade:{description:'Power rises to 80.', powerDelta:12} }),
  ability({ id:'brace', name:'Brace', affinity:'neutral', maxPP:8, target:'ally-one', description:'Target ally becomes Fortified for 2 turns.', effects:[{kind:'status', target:'ally-one', statusId:'fortified', duration:2}], upgrade:{description:'Fortified lasts 3 turns.', durationDelta:1} }),
  ability({ id:'signal-flare', name:'Signal Flare', affinity:'trick', maxPP:6, target:'enemy-all', description:'Apply Weaken to all enemies for 2 turns.', effects:[{kind:'status', target:'enemy-all', statusId:'weaken', duration:2}], upgrade:{description:'Weaken lasts 3 turns.', durationDelta:1} }),
  ability({ id:'full-cover', name:'Full Cover', affinity:'neutral', maxPP:4, target:'ally-all', description:'The party becomes Fortified for 1 turn.', effects:[{kind:'status', target:'ally-all', statusId:'fortified', duration:1}], upgrade:{description:'Fortified lasts 2 turns.', durationDelta:1} }),

  ability({ id:'sidearm', name:'Sidearm', affinity:'tech', maxPP:18, target:'enemy-one', description:'A compact reliable shot.', effects:[{kind:'damage', power:65, target:'enemy-one'}], upgrade:{description:'Power rises to 77.', powerDelta:12} }),
  ability({ id:'sentry-unit', name:'Sentry Unit', affinity:'tech', maxPP:7, target:'self', description:'Deploy a turret for 3 turns. It attacks after Hans acts.', effects:[{kind:'summon', summonId:'sentry', duration:3}], mechanicId:'hans-deploy', upgrade:{description:'The sentry deals 25% more damage.', summonPowerScale:1.25} }),
  ability({ id:'repair-drone', name:'Repair Drone', affinity:'tech', maxPP:6, target:'self', description:'Deploy a repair drone for 3 turns. It heals after Hans acts.', effects:[{kind:'summon', summonId:'repair-drone', duration:3}], mechanicId:'hans-deploy', upgrade:{description:'The repair drone heals 25% more.', summonPowerScale:1.25} }),
  ability({ id:'overclock', name:'Overclock', affinity:'tech', maxPP:4, target:'self', description:'Enhance and extend active deployables; with none, gain Haste.', effects:[], mechanicId:'hans-overclock', upgrade:{description:'Extends active deployables by 2 turns instead of 1.', durationDelta:1} }),

  ability({ id:'loaded-dice', name:'Loaded Dice', affinity:'trick', maxPP:16, target:'enemy-one', description:'Roll a variable 55–90 power result.', effects:[{kind:'damage', power:55, target:'enemy-one', mechanicId:'loaded-dice'}], mechanicId:'loaded-dice', upgrade:{description:'Roll 65–100 power instead.', powerDelta:10} }),
  ability({ id:'double-down', name:'Double Down', affinity:'trick', maxPP:7, target:'enemy-one', description:'60%: 110 power. 40%: 55 power and lose 12% Max HP.', effects:[{kind:'damage', power:110, target:'enemy-one', mechanicId:'double-down'}], mechanicId:'double-down', upgrade:{description:'Good outcome becomes 120 power.', powerDelta:10} }),
  ability({ id:'safe-bet', name:'Safe Bet', affinity:'neutral', maxPP:7, target:'enemy-one', description:'60 power, cannot miss; gain Fortified for 1 turn.', effects:[{kind:'damage', power:60, target:'enemy-one', mechanicId:'cannot-miss'},{kind:'status', target:'self', statusId:'fortified', duration:1}], mechanicId:'cannot-miss', upgrade:{description:'Fortified lasts 2 turns.', durationDelta:1} }),
  ability({ id:'all-in', name:'All In', affinity:'trick', maxPP:3, target:'enemy-one', description:'Sacrifice 20% current HP, then strike for 125 power.', effects:[{kind:'sacrificeHp', amount:0.20, basis:'current', floorAtOne:true},{kind:'damage', power:125, target:'enemy-one'}], upgrade:{description:'Power rises to 140.', powerDelta:15} }),

  ability({ id:'pan-smack', name:'Pan Smack', affinity:'might', maxPP:18, target:'enemy-one', description:'A sturdy pan strike.', effects:[{kind:'damage', power:62, target:'enemy-one'}], upgrade:{description:'Power rises to 74.', powerDelta:12} }),
  ability({ id:'hot-meal', name:'Hot Meal', affinity:'neutral', maxPP:7, target:'ally-one', description:'Heal 25% Max HP and grant Strength for 1 turn.', effects:[{kind:'heal', target:'ally-one', percentMaxHp:0.25},{kind:'status', target:'ally-one', statusId:'strength', duration:1, mechanicId:'positive-duration-plus-one'}], upgrade:{description:'Heal rises to 30% Max HP.', healScale:1.2} }),
  ability({ id:'full-plate', name:'Full Plate', affinity:'neutral', maxPP:6, target:'ally-one', description:'Grant Strength and Fortified for 2 turns.', effects:[{kind:'status', target:'ally-one', statusId:'strength', duration:2, mechanicId:'positive-duration-plus-one'},{kind:'status', target:'ally-one', statusId:'fortified', duration:2, mechanicId:'positive-duration-plus-one'}], upgrade:{description:'Base durations rise to 3 turns.', durationDelta:1} }),
  ability({ id:'chefs-table', name:"Chef's Table", affinity:'neutral', maxPP:3, target:'ally-all', description:'Heal the party for 16% Max HP and cleanse one negative status each.', effects:[{kind:'heal', target:'ally-all', percentMaxHp:0.16},{kind:'cleanse', target:'ally-all', count:1}], upgrade:{description:'Healing rises to 20% Max HP.', healScale:1.25} }),

  ability({ id:'shade-touch', name:'Shade Touch', affinity:'mystic', maxPP:18, target:'enemy-one', description:'A direct dark strike.', effects:[{kind:'damage', power:72, target:'enemy-one'}], upgrade:{description:'Power rises to 84.', powerDelta:12} }),
  ability({ id:'hex', name:'Hex', affinity:'mystic', maxPP:8, target:'enemy-one', description:'Damage and Weaken for 2 turns.', effects:[{kind:'damage', power:45, target:'enemy-one'},{kind:'status', target:'enemy-one', statusId:'weaken', duration:2}], upgrade:{description:'Weaken lasts 3 turns.', durationDelta:1} }),
  ability({ id:'life-drain', name:'Life Drain', affinity:'mystic', maxPP:6, target:'enemy-one', description:'70 power; heal Nathaniel for 35% of damage dealt.', effects:[{kind:'damage', power:70, target:'enemy-one', mechanicId:'life-drain'}], mechanicId:'life-drain', upgrade:{description:'Drain healing rises to 45% of damage.', healScale:1.286} }),
  ability({ id:'abyssal-pact', name:'Abyssal Pact', affinity:'mystic', maxPP:3, target:'enemy-all', description:'Spend 15% Max HP without self-KO, then damage all enemies.', effects:[{kind:'sacrificeHp', amount:0.15, basis:'max', floorAtOne:true},{kind:'damage', power:62, target:'enemy-all'}], upgrade:{description:'Power rises to 74.', powerDelta:12} }),

  ability({ id:'pedal-strike', name:'Pedal Strike', affinity:'might', maxPP:18, target:'enemy-one', description:'65 power; +15% damage if Yatords is faster than the target.', effects:[{kind:'damage', power:65, target:'enemy-one', mechanicId:'pedal-strike'}], mechanicId:'pedal-strike', upgrade:{description:'Power rises to 77.', powerDelta:12} }),
  ability({ id:'draft', name:'Draft', affinity:'neutral', maxPP:8, target:'ally-one', description:'Yatords and one ally gain Haste for 2 turns.', effects:[{kind:'status', target:'self', statusId:'haste', duration:2},{kind:'status', target:'ally-one', statusId:'haste', duration:2}], upgrade:{description:'Haste lasts 3 turns.', durationDelta:1} }),
  ability({ id:'drive-by', name:'Drive-By', affinity:'trick', maxPP:6, target:'enemy-one', description:'Three quick 22-power hits.', effects:[{kind:'damage', power:22, hits:3, target:'enemy-one'}], upgrade:{description:'Each hit rises to 26 power.', powerDelta:4} }),
  ability({ id:'breakaway', name:'Breakaway', affinity:'might', maxPP:4, target:'enemy-one', description:'80 base power +25 per Momentum; consumes all Momentum.', effects:[{kind:'damage', power:80, target:'enemy-one', mechanicId:'breakaway'}], mechanicId:'breakaway', upgrade:{description:'Base power rises to 90.', powerDelta:10} }),

  ability({ id:'bottle-tap', name:'Bottle Tap', affinity:'might', maxPP:18, target:'enemy-one', description:'A clean bottle strike.', effects:[{kind:'damage', power:65, target:'enemy-one'}], upgrade:{description:'Power rises to 77.', powerDelta:12} }),
  ability({ id:'house-pour', name:'House Pour', affinity:'trick', maxPP:7, target:'ally-one', description:"Target ally gains Strength for 2 turns. Don't ask what's in it.", effects:[{kind:'status', target:'ally-one', statusId:'strength', duration:2, mechanicId:'positive-duration-plus-one'}], upgrade:{description:'Base Strength lasts 3 turns.', durationDelta:1} }),
  ability({ id:'on-the-rocks', name:'On the Rocks', affinity:'trick', maxPP:7, target:'enemy-one', description:'50 power and Slow for 2 turns.', effects:[{kind:'damage', power:50, target:'enemy-one'},{kind:'status', target:'enemy-one', statusId:'slow', duration:2}], upgrade:{description:'Slow lasts 3 turns.', durationDelta:1} }),
  ability({ id:'last-call', name:'Last Call', affinity:'trick', maxPP:3, target:'enemy-all', description:'All enemies receive Weaken for 2 turns.', effects:[{kind:'status', target:'enemy-all', statusId:'weaken', duration:2}], upgrade:{description:'Weaken lasts 3 turns.', durationDelta:1} }),

  ability({ id:'scatter', name:'Scatter', affinity:'trick', maxPP:16, target:'random-enemy', description:'Four random 20-power hits; a lone enemy takes all four.', effects:[{kind:'damage', power:20, hits:4, target:'random-enemy'}], upgrade:{description:'Each hit rises to 24 power.', powerDelta:4} }),
  ability({ id:'markup', name:'Markup', affinity:'trick', maxPP:8, target:'enemy-one', description:'Apply Exposed for 2 turns.', effects:[{kind:'status', target:'enemy-one', statusId:'exposed', duration:2}], upgrade:{description:'Exposed lasts 3 turns.', durationDelta:1} }),
  ability({ id:'cashback', name:'Cashback', affinity:'neutral', maxPP:6, target:'enemy-one', description:'60 power; a KO grants 15 coins.', effects:[{kind:'damage', power:60, target:'enemy-one', mechanicId:'cashback'},{kind:'grantCoins', amount:15, trigger:'ko'}], upgrade:{description:'Power rises to 72.', powerDelta:12} }),
  ability({ id:'clearance-sale', name:'Clearance Sale', affinity:'trick', maxPP:3, target:'ally-all', description:'Spend 15 coins; party gains Strength and Haste for 2 turns.', effects:[{kind:'spendCoins', amount:15},{kind:'status', target:'ally-all', statusId:'strength', duration:2},{kind:'status', target:'ally-all', statusId:'haste', duration:2}], mechanicId:'clearance-sale', upgrade:{description:'Coin cost falls to 10.', coinCostDelta:-5} }),
];

export const CHARACTERS: CharacterDefinition[] = [
  { id:'earl', displayName:'Earl', affinity:'trick', role:'Healer / smoke debuffer / bruiser', stats:{maxHp:110,power:92,guard:95,speed:88}, passive:{id:'first-responder',name:'First Responder',description:"Earl's first heal each battle is 20% stronger."}, abilities:['knuckle-up','yosi','patch-up','adrenaline'], assetId:'character-earl', accentColor:'#C77B94' },
  { id:'greg', displayName:'Greg', affinity:'might', role:'Pirate attacker / plunder', stats:{maxHp:108,power:105,guard:88,speed:92}, passive:{id:'spoils',name:'Spoils',description:'First KO Greg scores each battle grants 5 bonus coins.'}, abilities:['cutlass','broadside','plunder','boarding-rush'], assetId:'character-greg' },
  { id:'michael', displayName:'Michael', affinity:'tech', role:'Soldier / reliable ranged damage', stats:{maxHp:104,power:110,guard:84,speed:100}, passive:{id:'steady-aim',name:'Steady Aim',description:"Michael's first damaging skill each battle cannot miss and deals 10% extra damage."}, abilities:['rifle-burst','grenade','suppressing-fire','rally'], assetId:'character-michael' },
  { id:'marcus', displayName:'Marcus', affinity:'tech', role:'Navy-themed defensive controller', stats:{maxHp:122,power:88,guard:115,speed:70}, passive:{id:'bulkhead',name:'Bulkhead',description:'Marcus begins each battle Fortified for 1 turn.'}, abilities:['deck-gun','brace','signal-flare','full-cover'], assetId:'character-marcus' },
  { id:'hans', displayName:'Hans', affinity:'tech', role:'Inventor / deployable summoner', stats:{maxHp:92,power:98,guard:80,speed:94}, passive:{id:'spare-parts',name:'Spare Parts',description:"Hans's first deployable each battle lasts one additional turn."}, abilities:['sidearm','sentry-unit','repair-drone','overclock'], assetId:'character-hans', accentColor:'#7A2E2E' },
  { id:'yeeho', displayName:'Yeeho', affinity:'trick', role:'Gambler / calculated risk', stats:{maxHp:96,power:104,guard:78,speed:108}, passive:{id:'house-edge',name:'House Edge',description:'The first poor Double Down outcome each battle refunds 1 PP.'}, abilities:['loaded-dice','double-down','safe-bet','all-in'], assetId:'character-yeeho' },
  { id:'jiro', displayName:'Jiro', affinity:'neutral', role:'Chef / healing and sustained buffs', stats:{maxHp:106,power:82,guard:92,speed:84}, passive:{id:'mise-en-place',name:'Mise en Place',description:'Positive statuses Jiro applies to allies last one additional turn.'}, abilities:['pan-smack','hot-meal','full-plate','chefs-table'], assetId:'character-jiro' },
  { id:'nathaniel', displayName:'Nathaniel', affinity:'mystic', role:'Dark entity / health-risk caster', stats:{maxHp:88,power:101,guard:76,speed:96}, passive:{id:'dark-hunger',name:'Dark Hunger',description:'Nathaniel gains 20% Power while below 40% HP.'}, abilities:['shade-touch','hex','life-drain','abyssal-pact'], assetId:'character-nathaniel' },
  { id:'yatords', displayName:'Yatords', affinity:'might', role:'Cyclist / speed and Momentum', stats:{maxHp:94,power:97,guard:82,speed:120}, passive:{id:'momentum',name:'Momentum',description:'Act before a living enemy to gain Momentum, max 3. Each stack grants +8% damage.'}, abilities:['pedal-strike','draft','drive-by','breakaway'], assetId:'character-yatords' },
  { id:'daboy', displayName:'Daboy', affinity:'trick', role:'Bartender / temporary buff and debuff specialist', stats:{maxHp:104,power:90,guard:96,speed:86}, passive:{id:'regulars-only',name:'Regulars Only',description:'Positive statuses Daboy applies to allies last one additional turn.'}, abilities:['bottle-tap','house-pour','on-the-rocks','last-call'], assetId:'character-daboy' },
  { id:'leandre', displayName:'Leandre', affinity:'trick', role:'Merchant / opportunistic economy utility', stats:{maxHp:100,power:92,guard:88,speed:98}, passive:{id:'good-business',name:'Good Business',description:'When Leandre is in the party, shops offer one additional inventory choice.'}, abilities:['scatter','markup','cashback','clearance-sale'], assetId:'character-leandre' },
];

const abilityMap = new Map(ABILITIES.map(item => [item.id, item]));
const characterMap = new Map(CHARACTERS.map(item => [item.id, item]));

export function getAbility(id: string): AbilityDefinition {
  const value = abilityMap.get(id);
  if (!value) throw new Error(`Unknown ability id: ${id}`);
  return value;
}

export function getCharacter(id: string): CharacterDefinition {
  const value = characterMap.get(id);
  if (!value) throw new Error(`Unknown character id: ${id}`);
  return value;
}

export function abilityMaxPp(characterId: string): Record<string, number> {
  const character = getCharacter(characterId);
  return Object.fromEntries(character.abilities.map(id => [id, getAbility(id).maxPP]));
}
