export const BALANCE = {
  affinityAdvantage: 1.5,
  affinityResistance: 0.75,
  damageVarianceMin: 0.95,
  damageVarianceMax: 1.05,
  criticalChance: 0.05,
  criticalMultiplier: 1.5,
  guardDamageMultiplier: 0.6,
  status: {
    strengthPowerMultiplier: 1.25,
    weakenPowerMultiplier: 0.75,
    hasteSpeedMultiplier: 1.25,
    slowSpeedMultiplier: 0.75,
    blindAccuracyMultiplier: 0.75,
    fortifiedDamageMultiplier: 0.7,
    exposedDamageMultiplier: 1.2,
  },
  enemyTierHpMultiplier: { normal: 1.85, elite: 1.45, boss: 1.55 },
  regionEnemyHpMultiplier: [1, 1.08, 1.16],
  regionEnemyPowerMultiplier: [1, 1.05, 1.10],
  inventoryCapacity: 6,
  restRecoverPercent: 0.35,
  restRefreshMissingPercent: 0.30,
  bossRecoveryHpPercent: 0.30,
  bossRecoveryMissingPpPercent: 0.25,
  maxDeployables: 2,
  leandreClearanceCoinCost: 15,
  yMomentumDamagePerStack: 0.08,
  maxMomentum: 3,
  shopBaseOffers: 4,
  regionCount: 3,
  routeStagesBeforeBoss: 6,
} as const;
