export const BALANCE = {
  affinityAdvantage: 1.5,
  affinityResistance: 0.75,
  damageVarianceMin: 0.95,
  damageVarianceMax: 1.05,
  criticalChance: 0.05,
  criticalMultiplier: 1.5,
  guardDamageMultiplier: 0.6,
  status: {
    strengthPowerMultiplier: 1.40,
    weakenPowerMultiplier: 0.70,
    hasteSpeedMultiplier: 1.25,
    slowSpeedMultiplier: 0.75,
    blindAccuracyMultiplier: 0.65,
    fortifiedDamageMultiplier: 0.6,
    exposedDamageMultiplier: 1.3,
  },
  enemyTierHpMultiplier: { normal: 1.65, elite: 1.45, boss: 1.45 },
  regionEnemyHpMultiplier: [1, 1.08, 1.16],
  regionEnemyPowerMultiplier: [1, 1.05, 1.10],
  inventoryCapacity: 6,
  restRecoverPercent: 0.35,
  restRefreshMissingPercent: 0.30,
  restReviveHpPercent: 0.10,
  postVictoryHpPercent: 0.12,
  bossRecoveryHpPercent: 0.45,
  bossRecoveryPpPerAbility: 2,
  regionReviveHpPercent: 0.25,
  maxDeployables: 2,
  leandreClearanceCoinCost: 15,
  yMomentumDamagePerStack: 0.08,
  // Breakaway converts stacks to power instead, so the passive percentage is not applied twice.
  yBreakawayPowerPerStack: 37,
  maxMomentum: 3,
  // Spec 03 Part B trial values. Unvalidated tuning hypotheses; Part C measures them.
  // Daboy's own Slow and Weaken are the setup; this is what they are worth to him.
  daboy: {
    houseSpecialDamageMultiplier: 1.45,
  },
  saq: {
    classMonitorPrevention: 8,
    correctiveActionDamageMultiplier: 1.25,
    dismissedReadyDamageMultiplier: 1.60,
  },
  // Spec 03 Part D trial values. Unvalidated tuning hypotheses; Part E measures them.
  ken: {
    inkMarkDamageMultiplier: 1.45,
    collaborativeWorkDamageBonus: 0.15,
    needleworkMarkDamageBonus: 0.20,
    scriptThresholdPercent: 0.20,
    scriptPreventPercent: 0.38,
    scriptPreventFloor: 10,
  },
  shopBaseOffers: 4,
  shopRerollBaseCost: 15,
  shopRerollCostStep: 15,
  regionCount: 3,
  routeStagesBeforeBoss: 6,
  relicTierWeights: {
    shop: [[78,20,2], [65,31,4], [50,43,7]],
    elite: [[72,25,3], [60,35,5], [48,44,8]],
    boss: [[50,44,6], [30,60,10], [0,85,15]],
    'folded-tokens': [[90,10,0], [90,10,0], [90,10,0]],
  },
  relicBasePrices: { common: 50, uncommon: 60, rare: 75 },
} as const;
